### ISSUE TITLE
DirectoryInfo.LastWriteTime throws FileNotFoundException on the root folder of a drive

### ISSUE THREAD

**Issue by thomaslevesque** [peteraritchie/LongPath#18]
```
System.IO.FileNotFoundException: File D:\ not found
File name: 'D:\'
   at Pri.LongPath.Common.ThrowIOError(Int32 errorCode, String maybeFullPath)
   at Pri.LongPath.FileSystemInfo.get_LastWriteTimeUtc()
   at Pri.LongPath.FileSystemInfo.get_LastWriteTime()
   at UserQuery.Main() in c:\Users\Tom\AppData\Local\Temp\LINQPad\_himmmwze\query_ijinft.cs:line 56
```

The same error occurs for all the creation/modification/las access properties.

In System.IO.DirectoryInfo, it works as expected.

**Comment by peteraritchie** [comment]
I've reproduced and I'll have a look at it, probably today.  thanks

**Comment by peteraritchie** [comment]
Added test to detect the problem and added fix.  FindFirstFile does not work with root dir and no wildcard--fix was to add a wildcard
